version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk wget unzip
      - wget https://services.gradle.org/distributions/gradle-4.4-bin.zip
      - mkdir /opt/gradle && unzip -d /opt/gradle gradle-4.4-bin.zip
      - export PATH=$PATH:/opt/gradle/gradle-4.4/bin
  build:
    commands:
      - gradle -v
      - gradle --debug distTar 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/distributions/shrtr.tar
