version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y gradle
      - apt-get install -y openjdk-8-jdk
  build:
    commands:
      - gradle --debug distTar 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/distributions/shrtr.tar
